#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "calcom"
name = "Cal.com"
description.en = "Scheduling infrastructure"
description.fr = "Scheduling infrastructure"

version = "3.5.3~ynh1"

maintainers = [""]

[upstream]
license = "free"
website = "https://cal.com/fr"
demo = "https://demo.example.com"
userdoc = "https://github.com/calcom/cal.com"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/calcom/cal.com/archive/refs/tags/v3.5.3.tar.gz"
        sha256 = "fe317d47827d1d68d65a7073fa4923aa45976a59a2093e88c2df0abff5c22f07"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
